# Generated by Django 3.0.8 on 2020-07-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=50, verbose_name='Наименование вопроса')),
                ('question_text', models.TextField(verbose_name='Вопрос')),
                ('question_answ1', models.CharField(max_length=50, verbose_name='Вариант1')),
                ('question_answ2', models.CharField(max_length=50, verbose_name='Вариант2')),
                ('question_answ3', models.CharField(max_length=50, verbose_name='Вариант3')),
                ('question_answ4', models.CharField(max_length=50, verbose_name='Вариант4')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
